when@test:
    twig:
        strict_variables: true  
twig:
    paths:
        '%kernel.project_dir%/Prolyfix/RssBundle/templates': 'RssBundle'
        '%kernel.project_dir%/Prolyfix/NoteBundle/templates': 'NoteBundle'
