when@test:
    twig:
        strict_variables: true  
twig:
    paths:
        '%kernel.project_dir%/dev/Prolyfix/RssBundle/templates': 'RssBundle'
        '%kernel.project_dir%/dev/Prolyfix/NoteBundle/templates': 'NoteBundle'
