vich_uploader:
    db_driver: orm
    mappings:
        medias:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/private/medias'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
