controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
prolyfix_datatables:
    resource: "@ProlyfixSymfonyDatatablesBundle/src/Controller"
    type:     attribute